{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "extraction-db-user"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "extraction-db-password"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "db-host"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "extraction-db"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "keycloak-certs-endpoint"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-enabled"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-driver"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "message-broker-connection-string"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "access-mode"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "default-command-channel"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_extraction.secretName }}
      type: Opaque
      data:
        - objectName: "extraction-db-user"
          key: extraction-db-user
        - objectName: "extraction-db-password"
          key: extraction-db-password
        - objectName: "db-host"
          key: db-host
        - objectName: "extraction-db"
          key: extraction-db
        - objectName: "keycloak-certs-endpoint"
          key: keycloak-certs-endpoint
        - objectName: "auth-enabled"
          key: auth-enabled
        - objectName: "message-broker-driver"
          key: message-broker-driver
        - objectName: "message-broker-connection-string"
          key: message-broker-connection-string
        - objectName: "access-mode"
          key: access-mode
        - objectName: "default-command-channel"
          key: default-command-channel
{{- end }}
