{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-database-host/versions/latest" 
        fileName: "db-host"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-extraction-db-user/versions/latest" 
        fileName: "extraction-db-user"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-extraction-db-password/versions/latest" 
        fileName: "extraction-db-password"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-extraction-db/versions/latest" 
        fileName: "extraction-db"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest" 
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest" 
        fileName: "message-broker-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest" 
        fileName: "keycloak-certs-endpoint"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/auth-enabled/versions/latest" 
        fileName: "auth-enabled"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/access-mode/versions/latest" 
        fileName: "access-mode"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/default-command-channel/versions/latest" 
        fileName: "default-command-channel"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_extraction.secretName }}
      type: Opaque
      data:
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
      - objectName: "db-host"
        key: db-host
      - objectName: "extraction-db-user"
        key: extraction-db-user
      - objectName: "extraction-db-password"
        key: extraction-db-password
      - objectName: "extraction-db"
        key: extraction-db
      - objectName: "access-mode"
        key: access-mode
      - objectName: "auth-enabled"
        key: auth-enabled
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
      - objectName: "default-command-channel"
        key: default-command-channel
{{- end }}
