secrets:
  extraction_database:
    secretName: extraction-database
  common_secret:
    secretName: common-secret
  database_ssl_secret:
    secretName: database-ssl-secret
  deps_extraction_migrator:
    secretName: deps-extraction-migrator

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.0"
  resources: {}

registry: ""
env: ""

migrator:
  image:
    path: "/deps-dev-x01/deps-extraction-migrator"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  args: ''

migration_settings:
  DATABASE_PORT: '5432'
  DATABASE_DIALECT: postgresql
  DATABASE_DRIVER: psycopg2
  DATABASE_REQUIRE_SECURE_TRANSPORT: false
  DATABASE_SSLKEY_PATH: '/home/dbcerts/tls.key'
  DATABASE_SSLCERT_PATH: '/home/dbcerts/tls.crt'
  DATABASE_SSLROOTCERT_PATH: '/home/dbcerts/root.crt'

certs_location:
  database_sslcerts_path: "/home/dbcerts"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

helm:
  enabled: false

csi:
  csi_default_name: deps-extraction-migrator
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

secret_project_id:
  id: ""

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

migrator_vault_enabled:
  env:
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: deps-extraction-migrator
        key: db-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: deps-extraction-migrator
        key: extraction-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: deps-extraction-migrator
        key: extraction-db-user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: deps-extraction-migrator
        key: extraction-db-password

migrator_vault_disabled:
  env:
  - name: MASTER_CHANGELOG
    value: "./migrations/master.yaml"
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: database-host
  - name: DATABASE_DB
    valueFrom:
      secretKeyRef:
        name: extraction-database
        key: database-db
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: extraction-database
        key: user
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: extraction-database
        key: password
