apiVersion: v1
kind: ConfigMap
metadata:
  name: extraction-configmap
  labels:
    {{- include "deps-extraction.labels" . | nindent 4 }}
data:
    ENV: {{ .Values.extraction_settings.ENV }}

    AUTH_VERIFY_SSL: '{{ .Values.extraction_settings.AUTH_VERIFY_SSL }}'

    LOG_LEVEL: '{{ .Values.extraction_settings.LOG_LEVEL }}'
    DOCUMENTATION_ENABLED: '{{ .Values.extraction_settings.DOCUMENTATION_ENABLED }}'

    AI_FUSION_URL: '{{ .Values.extraction_settings.AI_FUSION_URL }}'
    DOCUMENT_TYPE_URL: '{{ .Values.extraction_settings.DOCUMENT_TYPE_URL }}'

    KAFKA_GROUP_ID: '{{ .Values.extraction_settings.KAFKA_GROUP_ID }}'
    KAFKA_AUTO_OFFSET_RESET: '{{ .Values.extraction_settings.KAFKA_AUTO_OFFSET_RESET }}'

    DATABASE_PORT: '{{ .Values.extraction_settings.DATABASE_PORT }}'
    DATABASE_USER: '{{ .Values.extraction_settings.DATABASE_USER }}'
    DATABASE_DIALECT: '{{ .Values.extraction_settings.DATABASE_DIALECT }}'
    DATABASE_DRIVER: '{{ .Values.extraction_settings.DATABASE_DRIVER }}'
    DATABASE_REQUIRE_SECURE_TRANSPORT: '{{ .Values.extraction_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}'
    {{ if .Values.extraction_settings.DATABASE_REQUIRE_SECURE_TRANSPORT }}
    DATABASE_SSLKEY: {{ .Values.extraction_settings.DATABASE_SSLKEY_PATH }}
    DATABASE_SSLCERT: {{ .Values.extraction_settings.DATABASE_SSLCERT_PATH }}
    DATABASE_SSLROOTCERT: {{ .Values.extraction_settings.DATABASE_SSLROOTCERT_PATH }}
    {{ end }}


    {{ if .Values.extraction_settings.RABBITMQ_TLS_ENABLED }}
    RABBITMQ_TLS_HOST: '{{ .Values.extraction_settings.RABBITMQ_TLS_HOST }}'
    RABBITMQ_TLS_PORT: '{{ .Values.extraction_settings.RABBITMQ_TLS_PORT }}'
    RABBITMQ_TLS_USER: '{{ .Values.extraction_settings.RABBITMQ_TLS_USER }}'
    RABBITMQ_TLS_VHOST: '{{ .Values.extraction_settings.RABBITMQ_TLS_VHOST }}'
    RABBITMQ_TLS_SUBJECT: '{{ .Values.extraction_settings.RABBITMQ_TLS_SUBJECT }}'
    RABBITMQ_TLS_CA_CERT: '{{ .Values.extraction_settings.RABBITMQ_TLS_CA_CERT }}'
    RABBITMQ_TLS_CLIENT_CERT: '{{ .Values.extraction_settings.RABBITMQ_TLS_CLIENT_CERT }}'
    RABBITMQ_TLS_CLIENT_KEY: '{{ .Values.extraction_settings.RABBITMQ_TLS_CLIENT_KEY }}'
    {{ end }}

    {{ if .Values.extraction_settings.KAFKA_SECURITY_ENABLED }}
    KAFKA_SASL_MECHANISM: '{{ .Values.extraction_settings.KAFKA_SASL_MECHANISM }}'
    KAFKA_SECURITY_PROTOCOL: '{{ .Values.extraction_settings.KAFKA_SECURITY_PROTOCOL }}'
    {{ end }}
    {{ if .Values.extraction_settings.message_broker_asb_without_manage_permission }}
    ASB_SUBSCRIPTION_STRATEGY: '{{ .Values.extraction_settings.ASB_SUBSCRIPTION_STRATEGY }}'
    {{ end }}
    ASB_TOPIC_NAME: '{{ .Values.extraction_settings.ASB_TOPIC_NAME }}'

    # Telemetry
    INSTRUMENTATION_ENABLED: '{{ .Values.extraction_settings.INSTRUMENTATION_ENABLED }}'
    SERVICE_NAME: '{{ .Values.extraction_settings.SERVICE_NAME }}'
    EXPORTER_TYPE: '{{ .Values.extraction_settings.EXPORTER_TYPE }}'

    LLM_EXTRACTION_GROUPING_FACTOR: '{{ .Values.extraction_settings.LLM_EXTRACTION_GROUPING_FACTOR }}'
    EXTRACTION_WORKFLOW_ENABLED: '{{ .Values.extraction_settings.EXTRACTION_WORKFLOW_ENABLED }}'
